# Generated by Django 5.2.5 on 2025-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rescheduled_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
