# Generated by Django 5.2.5 on 2025-08-25 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_task_rescheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
