# Generated by Django 5.2.5 on 2025-08-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_stream_department_stream_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day_of_week', 'timeslot__start_time'], 'verbose_name_plural': 'Timetable Entries'},
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.timeslot'),
        ),
    ]
