# Generated by Django 5.2.5 on 2025-08-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0004_timeslot_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='non_academic_lectures_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='number_of_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_non_academic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professors',
            field=models.ManyToManyField(blank=True, to='timetable_app.professor'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.location'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.professor'),
        ),
    ]
