# Generated by Django 5.2.4 on 2025-08-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0005_stream_non_academic_lectures_per_week_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
